from __future__ import annotations

from torch.nn import utils as utils

from .rnn import LSTM, GRU, RNN
from .transformer import (
    Transformer,
    TransformerEncoder,
    TransformerEncoderLayer,
    TransformerDecoder,
    TransformerDecoderLayer,
)
from .multihead_attention import MultiheadAttention
from .functional import (
    relu,
    sigmoid,
    tanh,
    gelu,
    silu,
    leaky_relu,
    prelu,
    elu,
    celu,
    rrelu,
    glu,
    softmax,
    log_softmax,
    dropout,
    dropout2d,
    linear,
    bilinear,
    cross_entropy,
    mse_loss,
    binary_cross_entropy,
    binary_cross_entropy_with_logits,
    l1_loss,
    smooth_l1_loss,
    nll_loss,
    batch_norm,
    layer_norm,
    pad,
)
from .modules import (
    Module,
    Linear,
    Bilinear,
    Dropout,
    Dropout2d,
    BatchNorm1d,
    BatchNorm2d,
    LayerNorm,
    Sequential,
    ModuleList,
    ModuleDict,
    Parameter,
    ParameterList,
    ParameterDict,
    ReLU,
    Sigmoid,
    Tanh,
    GELU,
    SiLU,
    LeakyReLU,
    PReLU,
    ELU,
    CELU,
    RReLU,
    GLU,
    Softmax,
    LogSoftmax,
    Flatten,
    Unflatten,
    Identity,
    Conv1d,
    Conv2d,
    ConvTranspose2d,
    MaxPool2d,
    AvgPool2d,
    AdaptiveAvgPool2d,
    AdaptiveMaxPool2d,
    Embedding,
)

def __getattr__(name: str):
    if name == "init":
        import importlib
        return importlib.import_module("torch.nn.init")
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "relu",
    "sigmoid",
    "tanh",
    "gelu",
    "silu",
    "leaky_relu",
    "prelu",
    "elu",
    "celu",
    "rrelu",
    "glu",
    "softmax",
    "log_softmax",
    "dropout",
    "dropout2d",
    "linear",
    "bilinear",
    "cross_entropy",
    "mse_loss",
    "binary_cross_entropy",
    "binary_cross_entropy_with_logits",
    "l1_loss",
    "smooth_l1_loss",
    "nll_loss",
    "batch_norm",
    "layer_norm",
    "pad",
    "Module",
    "Linear",
    "Bilinear",
    "Dropout",
    "Dropout2d",
    "BatchNorm1d",
    "BatchNorm2d",
    "LayerNorm",
    "Sequential",
    "ModuleList",
    "ModuleDict",
    "Parameter",
    "ParameterList",
    "ParameterDict",
    "ReLU",
    "Sigmoid",
    "Tanh",
    "GELU",
    "SiLU",
    "LeakyReLU",
    "PReLU",
    "ELU",
    "CELU",
    "RReLU",
    "GLU",
    "Softmax",
    "LogSoftmax",
    "Flatten",
    "Unflatten",
    "Identity",
    "Conv1d",
    "Conv2d",
    "ConvTranspose2d",
    "MaxPool2d",
    "AvgPool2d",
    "AdaptiveAvgPool2d",
    "AdaptiveMaxPool2d",
    "Embedding",
    "LSTM",
    "GRU",
    "RNN",
    "MultiheadAttention",
    "Transformer",
    "TransformerEncoder",
    "TransformerEncoderLayer",
    "TransformerDecoder",
    "TransformerDecoderLayer",
]
