"""Real pretrained model: load a state_dict produced by real PyTorch, then
run inference in torch-pyodide and verify the output matches real PyTorch's
predictions bit-for-bit.

The model is a tiny 2-conv + 2-fc CNN trained on synthetic 3x16x16 data in
`scripts/train_pretrained_tiny_cnn.py`. The exported JSON bundle
(base64-encoded state_dict, sample input, and reference predictions) is
embedded directly into this file as a string literal so the example runs
unmodified in both real PyTorch and the playground.

This is the "Rodar modelos reais" smoke test: a state_dict that was
serialized by real PyTorch, transferred as a string, and reconstructed in
the browser must produce the same predictions.

DO NOT EDIT THIS FILE — it is generated by
`scripts/train_pretrained_tiny_cnn.py` from
`real_model_pretrained_tiny_cnn.template.py`. The generator replaces the
`__BUNDLE_JSON_PLACEHOLDER__` token with the latest JSON bundle.
"""
import base64
import io
import json

import torch
import torch.nn as nn
import torch.nn.functional as F


# ── Architecture — must match scripts/train_pretrained_tiny_cnn.py ──────
class TinyCNN(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(3, 8, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(8, 16, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(16 * 4 * 4, 32)
        self.fc2 = nn.Linear(32, 5)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)
        x = x.flatten(1)
        x = F.relu(self.fc1(x))
        return self.fc2(x)


# ── Bundle: serialized by real PyTorch, embedded here as a string literal ─
_BUNDLE_JSON = """__BUNDLE_JSON_PLACEHOLDER__"""

bundle = json.loads(_BUNDLE_JSON)

# ── Decode and load the state_dict produced by real PyTorch ─────────────
sd_bytes = base64.b64decode(bundle["state_dict_b64"])
state_dict = torch.load(io.BytesIO(sd_bytes), weights_only=False)

model = TinyCNN()
model.load_state_dict(state_dict)
model.eval()

# ── Run inference on the same sample input used in real PyTorch ─────────
sample_x = torch.tensor(bundle["sample_x"])
with torch.no_grad():
    logits = model(sample_x)
    probs = logits.softmax(dim=-1)
    preds = probs.argmax(dim=-1)

# ── Compare to the reference predictions baked into the bundle ──────────
ref = bundle["predictions"]
ref_preds = torch.tensor(ref["preds"])
ref_logits = torch.tensor(ref["logits"])
logits_max_abs_diff = float((logits - ref_logits).abs().max())
preds_match = bool((preds == ref_preds).all())

# ── Report the results as JSON ──────────────────────────────────────────
out = {
    "bundle_version": int(bundle.get("version", 0)),
    "n_samples": int(sample_x.shape[0]),
    "preds": [int(p) for p in preds.tolist()],
    "ref_preds": [int(p) for p in ref_preds.tolist()],
    "preds_match": preds_match,
    "logits_max_abs_diff": round(logits_max_abs_diff, 6),
    "first_pred": int(preds[0].item()),
    "first_pred_prob": round(float(probs[0, preds[0]].item()), 4),
    "first_ref_pred": int(ref_preds[0].item()),
    "state_dict_keys": sorted(state_dict.keys()),
    "training": bundle.get("training", {}),
}
print(json.dumps(out, indent=2))
