"""Real pretrained model: load a state_dict produced by real PyTorch, then
run inference in torch-pyodide and verify the output matches real PyTorch's
predictions bit-for-bit.

The model is a MiniVGG (small VGG-like CNN with BatchNorm2d + Dropout)
trained in real PyTorch on synthetic 3x16x16 data with Adam + StepLR.
The exported JSON bundle (base64-encoded state_dict, sample input, and
reference predictions) is embedded directly into this file as a string
literal so the example runs unmodified in both real PyTorch and the
playground.

This is the "Rodar modelos reais" smoke test for a more realistic
vision architecture: BatchNorm2d in eval mode (using running_mean /
running_var from the saved state_dict, not batch statistics), Dropout
disabled in eval mode, and a final classifier head.

DO NOT EDIT THIS FILE — it is generated by
`scripts/train_pretrained_vgg.py` from
`real_model_pretrained_vgg.template.py`. The generator replaces the
`__BUNDLE_JSON_PLACEHOLDER__` token with the latest JSON bundle.
"""
import base64
import io
import json

import torch
import torch.nn as nn
import torch.nn.functional as F


# ── Architecture — must match scripts/train_pretrained_vgg.py ──────
class MiniVGG(nn.Module):
    def __init__(self, num_classes: int = 5, dropout: float = 0.5) -> None:
        super().__init__()
        # Block 1: 3 -> 16 channels, 16x16 -> 8x8
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        # Block 2: 16 -> 32 channels, 8x8 -> 4x4
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(32)
        # Block 3: 32 -> 64 channels, 4x4 -> 2x2
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(64)
        # Classifier
        self.fc1 = nn.Linear(64 * 2 * 2, 64)
        self.fc2 = nn.Linear(64, num_classes)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.bn3(self.conv3(x)))
        x = F.max_pool2d(x, 2)
        x = x.flatten(1)
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        return self.fc2(x)


# ── Bundle: serialized by real PyTorch, embedded here as a string literal ─
_BUNDLE_JSON = """__BUNDLE_JSON_PLACEHOLDER__"""

bundle = json.loads(_BUNDLE_JSON)


# Recursive module iterator (torch-pyodide doesn't expose `Module.modules()` yet)
def _iter_modules(root):
    yield root
    for _, child in root.named_modules():
        if child is not root:
            yield child

# ── Decode and load the state_dict produced by real PyTorch ─────────────
sd_bytes = base64.b64decode(bundle["state_dict_b64"])
state_dict = torch.load(io.BytesIO(sd_bytes), weights_only=False)

model = MiniVGG()
model.load_state_dict(state_dict)
# `eval()` switches BatchNorm2d to use the saved running_mean / running_var
# (not the current batch's statistics) and disables Dropout. Without this,
# predictions would be both noisy (Dropout active) and wrong (BN using
# batch stats instead of the trained running stats).
model.eval()

# ── Run inference on the same sample input used in real PyTorch ─────────
sample_x = torch.tensor(bundle["sample_x"])

with torch.no_grad():
    # Full batch: same eval-mode behaviour as the reference.
    logits = model(sample_x)
    probs = logits.softmax(dim=-1)
    preds = probs.argmax(dim=-1)

# Batch-invariance check: in eval mode, BatchNorm2d uses the loaded
# running_mean / running_var instead of the current batch's statistics,
# so running each sample individually must give the same predictions as
# running them all together.
single_preds = []
with torch.no_grad():
    for i in range(len(sample_x)):
        single_preds.append(model(sample_x[i:i + 1]).argmax(dim=-1).item())
single_preds_tensor = torch.tensor(single_preds)
batch_invariant = bool((preds == single_preds_tensor).all())

# ── Compare to the reference predictions baked into the bundle ──────────
ref = bundle["predictions"]
ref_preds = torch.tensor(ref["preds"])
ref_logits = torch.tensor(ref["logits"])
logits_max_abs_diff = float((logits - ref_logits).abs().max())
preds_match = bool((preds == ref_preds).all())

# DEBUG: include state_dict sample values to diagnose load issue
debug_state_dict_samples = {
    "conv1.weight[:5]": state_dict["conv1.weight"].flatten()[:5].tolist(),
    "conv1.bias[:5]": state_dict["conv1.bias"].flatten()[:5].tolist(),
    "bn1.running_mean[:5]": state_dict["bn1.running_mean"].flatten()[:5].tolist(),
    "bn1.running_var[:5]": state_dict["bn1.running_var"].flatten()[:5].tolist(),
    "bn1.weight[:5]": state_dict["bn1.weight"].flatten()[:5].tolist(),
    "bn1.bias[:5]": state_dict["bn1.bias"].flatten()[:5].tolist(),
    "fc2.weight[0,:5]": state_dict["fc2.weight"][0].flatten()[:5].tolist(),
    "fc2.bias[:5]": state_dict["fc2.bias"].flatten()[:5].tolist(),
}
debug_model_params = {
    "conv1.weight[:5]": model.conv1.weight.flatten()[:5].tolist(),
    "bn1.running_mean[:5]": model.bn1.running_mean.flatten()[:5].tolist(),
    "bn1.running_var[:5]": model.bn1.running_var.flatten()[:5].tolist(),
}

# ── Report the results as JSON ──────────────────────────────────────────
out = {
    "bundle_version": int(bundle.get("version", 0)),
    "architecture": bundle.get("architecture", {}),
    "n_samples": int(sample_x.shape[0]),
    "preds": [int(p) for p in preds.tolist()],
    "ref_preds": [int(p) for p in ref_preds.tolist()],
    "preds_match": preds_match,
    "logits_max_abs_diff": round(logits_max_abs_diff, 6),
    "first_pred": int(preds[0].item()),
    "first_pred_prob": round(float(probs[0, preds[0]].item()), 4),
    "first_ref_pred": int(ref_preds[0].item()),
    "state_dict_keys": sorted(state_dict.keys()),
    "state_dict_n_keys": len(state_dict),
    "has_batchnorm_state": any("running_mean" in k for k in state_dict.keys()),
    "has_dropout_in_model": any(isinstance(m, nn.Dropout) for m in _iter_modules(model)),
    "batch_invariant_eval_mode": batch_invariant,
    "training": bundle.get("training", {}),
    "debug_state_dict_samples": debug_state_dict_samples,
    "debug_model_params": debug_model_params,
}
print(json.dumps(out, indent=2))
